const ControlActionTypes = {
  CORRECT_SPELL_INPUT: 'CORRECT_SPELL_INPUT',
  INCORRECT_SPELL_INPUT: 'INCORRECT_SPELL_INPUT',
  SPELL_INPUT_CHANGE: 'SPELL_INPUT_CHANGE',
  SPELL_SUBMIT: 'SPELL_SUBMIT',
};

export default ControlActionTypes;
